spring.application.name=SujetStage3A
spring.datasource.url=jdbc:postgresql://localhost:5432/Evaluation
spring.datasource.username=postgres
spring.datasource.password=amal
spring.datasource.driver-class-name=org.postgresql.Driver
# Server Configuration
server.port=8081
# Disable security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# PostgreSQL case sensitivity fix
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions=true


jwt.secret=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2





spring.mail.host=smtp.gmail.com 
spring.mail.port=587 
spring.mail.username=bejaouia975@gmail.com 
spring.mail.password=05112001@@ 
spring.mail.protocol=smtp 
spring.mail.properties.mail.smtp.auth=true 
spring.mail.properties.mail.smtp.starttls.enable=true 
spring.mail.properties.mail.smtp.connectiontimeout=5000 
spring.mail.properties.mail.smtp.timeout=5000 
spring.mail.properties.mail.smtp.writetimeout=5000
